TechStore/Pages/Cart/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using TechStore.Models;
using static System.Net.Mime.MediaTypeNames;

namespace TechStore.Pages.Cart
{
    
    public class CartModel : PageModel
    {

        public List<Product> SessionProductList { get; set; }
        public void OnGet()
        {
            if (HttpContext.Session.Keys.Contains("ProductList"))
            {
                var productListJson = HttpContext.Session.GetString("ProductList");
                SessionProductList = JsonConvert.DeserializeObject<List<Product>>(productListJson);
            }
        }
    }
    }

TechStore/Pages/Cart/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using TechStore.Data;
using TechStore.Models;
using TechStore.Repositories;

namespace TechStore.Pages.Cart
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<Client> _userManager;
        private readonly IAddressRepository _addressRepository;
        public List<Product> SessionProductList { get; set; }
        public Order Order { get; set; } = new Order();
        public decimal OrderValue { get; set; }
        [BindProperty]
        public Client Client { get; set; } = new Client();
        [BindProperty]
        public Address Address { get; set; } = new Address();
        public IndexModel(ApplicationDbContext context, UserManager<Client> userManager, IAddressRepository addressRepository)
        {
            _addressRepository = addressRepository;
            _context = context;
            _userManager = userManager;
        }
        public async Task OnGet()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                Client = user;
                var existingAddress = _addressRepository.GetAddressByClientId(user.Id);

                if (existingAddress != null)
                {
                    Address = existingAddress;
                }
            }
            if (HttpContext.Session.Keys.Contains("ProductList"))
            {
                var productListJson = HttpContext.Session.GetString("ProductList");
                SessionProductList = JsonConvert.DeserializeObject<List<Product>>(productListJson);
                foreach(var p in SessionProductList)
                {
                    OrderValue += p.Price;
                }
            }

        }
        public async void OnPostTest()
        {
            var user = await _userManager.GetUserAsync(User);

            if (user != null)
            {
                Client = user;
                var existingAddress = _addressRepository.GetAddressByClientId(user.Id);

                if (existingAddress != null)
                {
                    Address = existingAddress;
                }
            }
            if (HttpContext.Session.Keys.Contains("ProductList"))
            {
                var productListJson = HttpContext.Session.GetString("ProductList");
                SessionProductList = JsonConvert.DeserializeObject<List<Product>>(productListJson);
                foreach (var p in SessionProductList)
                {
                    OrderValue += p.Price;
                    
                }
            }
            ShippingAddress shippingAddress = new ShippingAddress();
            var maxId = _context.ShippingAddresses.Max(sa => (int?)sa.Id) ?? 0;
            shippingAddress.Id = maxId+1;
            shippingAddress.Street = Address.Street;
            shippingAddress.BuildingNumber = Address.BuildingNumber;
            shippingAddress.ApartmentNumber = Address.ApartmentNumber;
            shippingAddress.Locality = Address.Locality;
            shippingAddress.PostalCode = Address.PostalCode;
            _context.ShippingAddresses.Add(shippingAddress);
            _context.SaveChanges();
            Order.ShippingAddressId = shippingAddress.Id;
            Order.OrderStatus = "W realizacji";
            Order.OrderDate = DateTime.Now;
            Order.OrderValue = (double)OrderValue;
            Order.ClientId = Client.Id;
            Order.OrderConfirmation = true;
            Order.CompletionConfirmation = true;
            var OrderId = _context.Orders.Max(sa => (int?)sa.Id) ?? 0;
            Order.Id=OrderId+1;
            _context.Orders.Add(Order);
            _context.SaveChanges();
            ProductOrderRelation productOrderRelation = new ProductOrderRelation();
            foreach (var p in SessionProductList)
            {
                productOrderRelation.ProductId = p.Id;
                productOrderRelation.OrderId = Order.Id;
                productOrderRelation.Quantity = 1;
                _context.ProductOrderRelations.Add(productOrderRelation);
                _context.SaveChanges();

            }
        }
    }
}

TechStore/Pages/Cart/View.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TechStore.Pages.Cart
{
    public class ViewModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

TechStore/Pages/Cart/Cart.cshtml
@page
@using TechStore.Models;
@model CartModel
@{
    ViewData["Title"] = "Twój Koszyk";
}

<link rel="stylesheet" href="~/css/cart.css" />

<a title="TechStore" style="font-style: oblique;" href="/">TechStore</a>
<img src="~/images/arrow.svg" class="icon-dark-mode" loading="lazy" alt="Koszyk" style="height: 1em; vertical-align: middle;"> Twój koszyk

<div class="cart-header">
    <div class="header-content">
        <h2>Koszyk</h2>
        <div class="cart-actions">
            <button class="save-list-button">
                <img src="~/images/save-icon.svg"  alt="Save" /> Zapisz jako listę
            </button>

            <button class="clear-cart-button">
                <img src="~/images/clear-icon.svg"  alt="Clear" /> Wyczyść koszyk
            </button>

        </div>
    </div>
</div>

<div class="cart-body">
    <div class="cart-products">
        @if (Model.SessionProductList != null && Model.SessionProductList.Any())
        {
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Miniatura</th>
                            <th>Nazwa</th>
                            <th>Cena</th>
                            <th>Ilość</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var groupedProduct in Model.SessionProductList.GroupBy(p => p.Id))
                        {
                            var firstProduct = groupedProduct.First();
                            <tr>
                                <td>@firstProduct.Id</td>
                                <td>
                                    <img src="@firstProduct.Image" alt="Miniatura" style="max-width: 90px; max-height: 90px;" />
                                </td>
                                <td>@firstProduct.Name</td>
                                <td>@firstProduct.Price zł</td>
                                <td>
                                    <select class="custom-select custom-select-sm quantity-dropdown" data-product-id="@firstProduct.Id" data-product-price="@firstProduct.Price">
                                     @for (int i = 1; i <= 10; i++)
                                        {
                                            <option value="@i" selected="@(i == groupedProduct.Count())">@i</option>
                                         }
                                    </select>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        }


        else
        {
            <br />
        <div class="cart-empty">
            
            <h3>Twój koszyk jest pusty.</h3>
            <p>Dodaj produkty do koszyka.</p>
                <a href="/Index" class="continue-shopping-button">Kontynuuj zakupy</a>
        </div>
        }

    </div>
   
    <div class="cart-summary">
        <div class="promo-code">

            <button class="promo-code-toggle" onclick="togglePromoCode()">
                Masz kod promocyjny?
                <img src="~/images/arrow-down.svg" class="arrow" alt="Toggle" />
            </button>

            <div class="promo-code-input" style="display: none;">
                <input type="text" id="promoCode" placeholder="Wprowadź kod" />
                <button class="apply-discount-button" onclick="applyPromoCode()">Zastosuj
                    <img src="~/images/discount.svg" class="icon-dark-mode" alt="Discount" />
                </button>
            </div>
        </div>

        <div class="total-amount">
            <h3>
                Łączna kwota: <td>
                    @{

                        if (Model.SessionProductList != null && Model.SessionProductList.Any())
                        {
                            decimal total = Model.SessionProductList.Sum(p => p.Price);
                            <span>@total</span>
                        } 
                    } ZŁ
                </td>
            </h3>
             </div>

        <div class="checkout-actions">
            <a asp-page="/Cart/Index" class="delivery-button">Przejdź do dostawy
                <img src="~/images/cart-submit.svg" alt="Buy" />
            </a>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12 divider"></div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="contact-category">
                <h3>
                    <img src="~/images/safe.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Chat" /> Bezpieczne zakupy
                </h3>
                Dzięki szyfrowaniu TLS
            </div>
        </div>


        <div class="col-md-4">
            <div class="contact-category">
                <h3>
                    <img src="~/images/return-box.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Chat" /> Darmowe zwroty
                </h3>
                Darmowa dostawa do 14 dni. Paczkomatem lub w naszych salonach
            </div>
        </div>


        <div class="col-md-4">
            <div class="contact-category">
                <h3>
                    <img src="~/images/support.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Chat" /> Wsparcie techniczne
                </h3>
                E-mail, telefon i czat
            </div>

        </div>
    </div>
</div>


<script src="~/js/cart.js"></script>

TechStore/Pages/Cart/Index.cshtml
@page
@model TechStore.Pages.Cart.IndexModel
@{
    ViewData["Title"] = "Złóż zamówienie";
}

<link rel="stylesheet" href="~/css/shipping.css" />

<div class="container mt-5">

    <div class="row mt-5">
        <div class="col-md-8 mx-auto">
            <div class="card shadow-lg border-primary">
                <div class="card-body bg-light text-center">
                    <a href="/cart/cart" class="btn btn-link mb-3">Wróć do koszyka</a>
                    <p class="text-primary font-weight-bold">Dostawa: <span class="text-secondary">Za darmo</span></p>
                    <hr />
                    <p class="text-primary font-weight-bold">Do zapłaty: <span class="text-success">@Model.OrderValue ZŁ</span></p>
                </div>
            </div>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-8 mx-auto">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Address.Street" class="form-label">Nazwa ulicy:</label>
                    <input asp-for="Address.Street" class="form-control" aria-required="true" />
                    <span asp-validation-for="Address.Street" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Address.BuildingNumber" class="form-label">Numer budynku:</label>
                    <input asp-for="Address.BuildingNumber" class="form-control" aria-required="true" />
                    <span asp-validation-for="Address.BuildingNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Address.ApartmentNumber" class="form-label">Numer mieszkania (opcjonalnie):</label>
                    <input asp-for="Address.ApartmentNumber" class="form-control" aria-required="false" />
                    <span asp-validation-for="Address.ApartmentNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Address.PostalCode" class="form-label">Kod pocztowy:</label>
                    <input asp-for="Address.PostalCode" class="form-control" aria-required="true" />
                    <span asp-validation-for="Address.PostalCode" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Address.Locality" class="form-label">Miasto:</label>
                    <input asp-for="Address.Locality" class="form-control" aria-required="true" />
                    <span asp-validation-for="Address.Locality" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Client.FirstName" class="form-label">Imię:</label>
                    <input asp-for="Client.FirstName" class="form-control" aria-required="true" />
                    <span asp-validation-for="Client.FirstName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Client.LastName" class="form-label">Nazwisko:</label>
                    <input asp-for="Client.LastName" class="form-control" aria-required="true" />
                    <span asp-validation-for="Client.LastName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Client.PhoneNumber" class="form-label">Tel:</label>
                    <input asp-for="Client.PhoneNumber" class="form-control" aria-required="true" />
                    <span asp-validation-for="Client.PhoneNumber" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Client.Email" class="form-label">Email:</label>
                    <input asp-for="Client.Email" class="form-control" aria-required="true" />
                    <span asp-validation-for="Client.Email" class="text-danger"></span>
                </div>

                <button type="submit" asp-page-handler="Test" class="btn btn-primary btn-lg w-100 mt-3">Złóż zamówienie</button>
            </form>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-8 mx-auto text-center">
            <button type="button" id="addCommentButton" class="btn btn-secondary">Uwagi do zamówienia</button>

            <div id="commentSection" class="mt-3" style="display: none;">
                <textarea id="orderComment" name="orderComment" class="form-control" placeholder="Wpisz komentarz..." rows="4"></textarea>
            </div>
        </div>
    </div>
</div>

<script src="~/js/shipping.js"></script>

TechStore/Pages/Cart/Shipping.cshtml
@page
@model TechStore.Pages.Cart.CartModel

@{
    ViewData["Title"] = "Złóż zamówienie";
}

<link rel="stylesheet" href="~/css/shipping.css" />

<div class="container">
    <div class="form-container">
        <form method="post">
            <div class="form-row">

                <h2>Dane odbiorcy przesyłki</h2>

                <div class="recipient-type-container">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="recipientType" id="privatePerson" value="privatePerson" checked onchange="toggleFormType('private')">
                        <label class="form-check-label" for="privatePerson">Osoba prywatna</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="recipientType" id="company" value="company" onchange="toggleFormType('company')">
                        <label class="form-check-label" for="company">Firma</label>
                    </div>
                </div>


                
 <div id="privateForm">
     
     <div class="form-row">
                <div class="form-group col">
                    <label for="firstName">Imię:</label>
                    <input type="text" id="firstName" name="firstName" class="form-control" required />
                </div>
                <div class="form-group col">
                    <label for="lastName">Nazwisko:</label>
                    <input type="text" id="lastName" name="lastName" class="form-control" required />
                </div>
            </div>
                
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" class="form-control" required />
            </div>

            <div class="form-group">
                <label for="phone">Nr telefonu:</label>
                <input type="tel" id="phone" name="phone" class="form-control" placeholder="+48 ___ ___ ___" required />
            
            </div>


            <div class="form-row">
                <div class="form-group col">
                    <label for="address">Ulica i numer domu:</label>
                    <input type="text" id="address" name="address" class="form-control" required />
                </div>
                <div class="form-group col">
                    <label for="postalCode">Kod pocztowy:</label>
                    <input type="text" id="postalCode" name="postalCode" class="form-control" placeholder="__-___" required />
                </div>
                <div class="form-group col">
                    <label for="city">Miejscowość:</label>
                    <input type="text" id="city" name="city" class="form-control" required />
                </div>
            </div>
        </div>
</div>


 <div id="companyForm" style="display: none;">
    
     <div class="form-group">
        <label for="companyName">Nazwa firmy:</label>
        <input type="text" id="companyName" name="companyName" class="form-control" required />
    </div>

    <div class="form-group">
        <label for="nip">NIP:</label>
        <input type="text" id="nip" name="nip" class="form-control" placeholder="_______" required />
    </div>

    <div class="form-group">
        <label for="companyEmail">Email:</label>
        <input type="email" id="companyEmail" name="companyEmail" class="form-control" required />
    </div>

    <div class="form-group">
        <label for="companyPhone">Nr telefonu:</label>
        <input type="tel" id="companyPhone" name="companyPhone" class="form-control" placeholder="+48 ___ ___ ___" required />
    </div>

    <div class="form-row">
        <div class="form-group col">
            <label for="companyAddress">Ulica i numer domu:</label>
            <input type="text" id="companyAddress" name="companyAddress" class="form-control" required />
        </div>
        <div class="form-group col">
            <label for="companyPostalCode">Kod pocztowy:</label>
            <input type="text" id="companyPostalCode" name="companyPostalCode" class="form-control" placeholder="__-___" required />
        </div>
        <div class="form-group col">
            <label for="companyCity">Miejscowość:</label>
            <input type="text" id="companyCity" name="companyCity" class="form-control" required />
        </div>
    </div>
</div>

            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="newsletter">
                <label class="form-check-label" for="newsletter">Chcę dostawać newsletter i korzystać ze specjalnych promocji</label>
            </div>


        </form>
    </div>

        <div class="order-summary-container sticky-summary mt-5">
            


            <div class="order-summary-details">
                <p>Wartość produktów: <span></span></p>
                <p>Dostawa: <span>13,90 zł</span></p>
                <div class="order-summary-line"></div>
                <p>Do zapłaty: <span>10011,92 zł</span></p>
            </div>
            <button type="submit" class="btn btn-primary order-submit-button">Złóż zamówienie</button>

        </div>

    

</div>

<form method="post">

<div class="delivery-payment">
    <h2>Dostawa</h2>

    <div class="custom-radio">
    <input type="radio" id="kurierExpress" name="deliveryOption" value="kurierExpress">
    <label class="radio-label" for="kurierExpress">
        <img src="~/images/dpd_logo.png" alt="Kurier DPD" class="radio-image">
        <span>Kurier DPD</span>
        <span class="radio-description">U Ciebie za ok. 5 dni (środa)</span>
        <span>15,99 zł</span>
        <span class="checkmark"></span>
    </label>
</div>


<div class="custom-radio">
    <input type="radio" id="kurierStandard" name="deliveryOption" value="kurierStandard">
    <label class="radio-label" for="kurierStandard">
        <img src="~/images/gls.png" alt="Kurier GLS" class="radio-image">
        <span>Kurier GLS</span>
        <span class="radio-description">U Ciebie za ok. 6 dni (czwartek)</span>
        <span>13,90 zł</span>
        <span class="checkmark"></span>
    </label>
</div>



<div class="custom-radio">
    <input type="radio" id="inpost" name="deliveryOption" value="inpost">
    <label class="radio-label" for="inpost">
        <img src="~/images/inpost.svg.png" alt="Paczkomaty Inpost" class="radio-image">
        <span>Paczkomaty Inpost</span>
        <span class="radio-description">U Ciebie za ok. 3 dni (poniedziałek)</span>
        <span>9,99 zł</span>
        <span class="checkmark"></span>
    </label>
</div>



<div class="custom-radio">
    <input type="radio" id="ups" name="deliveryOption" value="ups">
    <label class="radio-label" for="ups">
        <img src="~/images/ups.png" alt="Kurier UPS" class="radio-image">
        <span>Kurier UPS</span>
        <span class="radio-description">U Ciebie za ok. 10 dni (poniedziałek)</span>
        <span>16,50 zł</span>
        <span class="checkmark"></span>
    </label>
</div>



<div class="custom-radio">
    <input type="radio" id="orlen" name="deliveryOption" value="orlen">
    <label class="radio-label" for="orlen">
        <img src="~/images/orlen.png" alt="Orlen paczka" class="radio-image">
        <span>Orlen paczka</span>
        <span class="radio-description">U Ciebie za ok. 3 dni (poniedziałek)</span>
        <span>10,90 zł</span>
        <span class="checkmark"></span>
    </label>
</div>



<div class="custom-radio">
    <input type="radio" id="osobisty" name="deliveryOption" value="osobisty">
    <label class="radio-label" for="osobisty">
        <img src="~/images/odbior.svg" alt="Odbiór osobisty" class="radio-image">
        <span>Odbiór osobisty</span>
        <span class="radio-description">W sklepach stacjonarnych</span>
        <span>Za darmo</span>
        <span class="checkmark"></span>
    </label>
</div>
   

</div>

</form>


<form method="post">

<div class="delivery-payment">
    <h2>Płatność</h2>

    <div class="custom-radio">
    <input type="radio" id="blik" name="deliveryOption" value="blik">
    <label class="radio-label" for="blik">
        <img src="~/images/blik.png" alt="blik" class="radio-image">
        <span>BLIK</span>
        <span class="checkmark"></span>
    </label>
</div>


   <div class="custom-radio">
    <input type="radio" id="card" name="deliveryOption" value="card">
    <label class="radio-label" for="card">
        <img src="~/images/card.jpg" alt="card" class="radio-image">
        <span>Karta płatnicza online</span>
        <span class="checkmark"></span>
    </label>
</div>


   <div class="custom-radio">
    <input type="radio" id="przelew" name="deliveryOption" value="przelew">
    <label class="radio-label" for="przelew">
        <img src="~/images/przelew.png" alt="przelew" class="radio-image">
        <span>Przelew błyskawiczny</span>
        <span class="checkmark"></span>
    </label>
</div>



   <div class="custom-radio">
    <input type="radio" id="google" name="deliveryOption" value="google">
    <label class="radio-label" for="google">
        <img src="~/images/google.png" alt="google" class="radio-image">
        <span>Google Pay</span>
        <span class="checkmark"></span>
    </label>
</div>


   <div class="custom-radio">
    <input type="radio" id="tradycyjny" name="deliveryOption" value="tradycyjny">
    <label class="radio-label" for="tradycyjny">
        <img src="~/images/tradycyjny.svg" alt="tradycyjny" class="radio-image">
        <span>Przelew tradycyjny</span>
        <span class="checkmark"></span>
    </label>
</div>



   <div class="custom-radio">
    <input type="radio" id="raty" name="deliveryOption" value="raty">
    <label class="radio-label" for="raty">
        <img src="~/images/raty.png" alt="raty" class="radio-image">
        <span>Raty</span>
        <span class="checkmark"></span>
    </label>
</div>


   <div class="custom-radio">
    <input type="radio" id="paypo" name="deliveryOption" value="paypo">
    <label class="radio-label" for="paypo">
        <img src="~/images/paypo.png" alt="paypo" class="radio-image">
        <span>PayPo - zapłać za 30 dni</span>
        <span class="checkmark"></span>
    </label>
</div>

</div>

</form>


<br />
<div class="additional-options">
    <a href="/cart/cart" class="back-to-cart">Wróć do koszyka</a>
    <br />
    <button type="button" id="addCommentButton" class="btn-add-comment">Uwagi do zamówienia</button>
    
    
    <div id="commentSection" style="display: none;">
        <textarea id="orderComment" name="orderComment" placeholder="Wpisz komentarz..." rows="4"></textarea>
    </div>
</div>

    <script src="~/js/shipping.js"></script>

TechStore/Pages/Cart/View.cshtml
@page
@model TechStore.Pages.Cart.ViewModel
@{
}