TechStore/Models/Product.cs
namespace TechStore.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public decimal Price { get; set; }
        public string? Description { get; set; }
        public int? Quantity { get; set; }
        public string? Image { get; set; }
        public string? Company { get; set; }
        public int CategoryId { get; set; }
        public bool IsOnSale { get; set; }
        public double? SalePrice { get; set; }
        public string? Url { get; set; }
        public Category? Category { get; set; }
        public List<Review>? Reviews { get; set; }
        public ProductSpecification? Specification { get; set; }
        public List<ProductOrderRelation>? ProductOrderRelations { get; set; }
        public List<Description>? Descriptions { get; set; }
        public List<ProductImage>? ProductImages { get; set; }
    }
}

TechStore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TechStore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TechStore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TechStore.Models;
using TechStore.Repositories;

namespace TechStore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IProductSpecificationRepository _specificationRepository;
        private readonly IProductRepository _productRepository;

        public List<Product> ProductsWithSpecifications { get; set; }

        public List<ProductSpecification> Specifications { get; set; }


        public IndexModel(IProductRepository productRepository, IProductSpecificationRepository specificationRepository)
        {
            _productRepository = productRepository;
            _specificationRepository = specificationRepository;
        }
        public void OnGet()
        {
            List<Product> productList = _productRepository.ReadProducts();

            Specifications = _specificationRepository.GetAll();

            ProductsWithSpecifications = productList.Select(product =>
            {
                product.Specification = Specifications.FirstOrDefault(spec => spec.ProductId == product.Id);
                return product;
            }).ToList();



        }
    }
}

TechStore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
namespace TechStore.Pages
{
    
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TechStore/Pages/Productdetail.cshtml.cs
using TechStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Threading.Tasks;
using TechStore.Repositories;
using Microsoft.AspNetCore.Components;

namespace TechStore.Pages
{
    public class OpiniaPageModel : PageModel
    {
        private readonly IOpiniaRepository _opiniaRepository;
        private readonly IProductRepository _productRepository;
        private readonly IProductSpecificationRepository _specificationRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public OpiniaPageModel(IOpiniaRepository opiniaRepository, IProductRepository productRepository, IProductSpecificationRepository specificationRepository, IHttpContextAccessor httpContextAccessor)
        {
            _opiniaRepository = opiniaRepository;
            _productRepository = productRepository;
            _specificationRepository = specificationRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        [BindProperty]
        public Opinia Opinia { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public int ProductId { get; set; }
        public ProductSpecification ProductSpecification { get; set; }
        public Product Product { get; private set; }
        public List<Product> ProductsWithSpecifications { get; set; }
        public List<ProductSpecification> Specifications { get; set; }

        public void OnGet()
        {
            Product = _productRepository.GetProductById(Id);
            ProductSpecification = _specificationRepository.GetByProductId(Id);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            Opinia.Data = DateTime.Now;

            await Task.Run(() => _opiniaRepository.AddAsync(Opinia));

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRateAsync(string category, int rating)
        {
            await Task.Run(() => _opiniaRepository.AddAsync(Opinia));

            return new JsonResult(new { success = true, message = "Ocena zapisana." });
        }

        public IActionResult OnPostAddToSession()
        {
            List<Product> sessionProductList;

            if (_httpContextAccessor.HttpContext.Session.Keys.Contains("ProductList"))
            {
                // Retrieve existing session list
                var productListJson = _httpContextAccessor.HttpContext.Session.GetString("ProductList");
                sessionProductList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Product>>(productListJson);
            }
            else
            {
                // Create a new session list if it doesn't exist
                sessionProductList = new List<Product>();
            }

            // Add the selected product to the session list
            Product selectedProduct = _productRepository.GetProductById(Id);
            sessionProductList.Add(selectedProduct);

            // Save the updated session list
            var updatedProductListJson = Newtonsoft.Json.JsonConvert.SerializeObject(sessionProductList);
            _httpContextAccessor.HttpContext.Session.SetString("ProductList", updatedProductListJson);

            return RedirectToPage();
        }
    }
}

TechStore/Pages/Index.cshtml
@page
@model IndexModel
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Home page";
}
<div id="banner-reklamowy" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active c-item">
            <img src="~/images/slider1.jpg" class="d-block w-100 c-img" alt="...">
            <div class="carousel-caption top-0 mt-4" style="margin-left: 10rem;">
                <p class="mt-5 fs-4 text-uppercase">@Localizer["Rabaty nawet do 50%"]</p>
                <h1 class="display-1 fw-bolder text-capitalize">@Localizer["Wyprzedaż smartfonów!"]</h1>
            </div>
        </div>
        <div class="carousel-item c-item">
            <img src="~/images/slider2.jpg" class="d-block w-100 c-img" alt="...">
            <div class="carousel-caption top-0 mt-4" style="margin-right: 15rem; text-align: left">
                <p class="mt-5 fs-4 text-uppercase">@Localizer["Odkryj mobilność i wydajność już teraz"]</p>
                <h1 class="display-1 fw-bolder text-capitalize">@Localizer["Twój nowy laptop czeka!"]</h1>
            </div>
        </div>
        <div class="carousel-item c-item">
            <img src="~/images/slider3.jpg" class="d-block w-100 c-img" alt="...">
            <div class="carousel-caption top-0" style="margin-left: 15rem; text-align: right">
                <p class="mt-5 fs-4 text-uppercase">@Localizer["Dostawa na nasz koszt"]</p>
                <h1 class="display-1 fw-bolder text-capitalize">@Localizer["Zamów i ciesz się darmową wysyłką!"]</h1>
            </div>
        </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#banner-reklamowy" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#banner-reklamowy" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="row">
    <div class="col-md-12 divider"></div>
</div>

<div class="text-center">
    <div class="container" id="product-cards-1">
        <h1 class="text-center">@Localizer["Polecamy"]</h1>
        <div class="row" style="margin-top: 30px;">
            @{
                var shuffledProducts1 = Model.ProductsWithSpecifications.OrderBy(p => Guid.NewGuid()).ToList();
                var randomProducts1 = shuffledProducts1.Take(4);
            }

            @foreach (var product in randomProducts1)
            {
                <div class="col-md-3 py-3 py-md-0">
                    <a href="/ProductDetails/@product.Id" class="text-decoration-none">
                        <div class="card">
                            <img src="@product.Image" alt="@product.Name" class="card-img-top">
                            <div class="card-body">
                                <h3 class="card-title">@product.Name</h3>
                                <h5 class="card-text">@String.Format("{0:C}", product.Price) <span><i class="fa fa-shopping-cart fa-lg"></i></span></h5>
                            </div>
                        </div>
                    </a>
                </div>

            }
        </div>
    </div>
    <a asp-page="/Products" id="viewmorebtn">Więcej</a>
</div>
<br />
<div class="row">
    <div class="col-md-12 divider"></div>
</div>
<div class="text-center">
    <div class="container" id="product-cards-2">
        <h1 class="text-center">@Localizer["Bestsellery"]</h1>
        <div class="row" style="margin-top: 30px;">
            @{
                var shuffledProducts2 = Model.ProductsWithSpecifications.OrderBy(p => Guid.NewGuid()).ToList();
                var randomProducts2 = shuffledProducts2.Take(4);
            }

            @foreach (var product in randomProducts2)
            {
                <div class="col-md-3 py-3 py-md-0">
                    <div class="card">
                        <img src="@product.Image" alt="">
                        <div class="card-body">
                            <h3>@product.Name</h3>
                            <h5>@String.Format("{0:C}", product.Price) <span><i class="fa fa-shopping-cart fa-lg"></i></span></h5>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <a asp-page="/Products" id="viewmorebtn">Więcej</a>
</div>

<br />
<br />

<div class="row">
    <div class="col-md-12 divider"></div>
</div>
<div class="album contenti">
    <div class="container">
        <h1 class="text-center">@Localizer["Promocje"]</h1>
        <div class="row">
            @{
                var shuffledProducts3 = Model.ProductsWithSpecifications.OrderBy(p => Guid.NewGuid()).ToList();
                var randomProducts3 = shuffledProducts3.Take(4);
            }
            @foreach (var product in randomProducts3)
            {
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="product-wrapper">
                        @if (product.IsOnSale)
                        {
                            <img class="fa fa-money" />
                        }
                        <div class="item">
                            <a href="@product.Url">
                                <img src="@product.Image" alt="Thumbnail" style="width: 100%; display: block;" data-holder-render="true" />
                            </a>
                            <div class="description">
                                <a href="@product.Url">@product.Name</a>
                                <div class="price">
                                    @if (product.IsOnSale)
                                    {
                                        <h4 class="currentPrice" style="float:left; margin-right: 10px;">PLN @product.SalePrice</h4>
                                        <label class="oldPrice">PLN @product.Price</label>
                                    }
                                    else
                                    {
                                        <h4 class="currentPrice">PLN @product.Price</h4>
                                    }
                                </div>
                            </div>
                            <div class="action text-center">
                                <a href="/ProductDetails/@product.Id" class="btn">Więcej</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 divider"></div>
</div>

TechStore/Pages/Kontakt.cshtml
@page
@using TechStore.Pages.Kontakt
@model KontaktModel
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Kontakt";
}

<link rel="stylesheet" href="~/css/kontakt.css" />

<a title="TechStore" style="font-style: oblique;" href="/">TechStore</a>
<img src="~/images/arrow.svg" loading="lazy" alt="Kontakt" style="height: 1em; vertical-align: middle;"> @Localizer["head"]

<div style="text-align: left;">
    <h2 style="font-size: 50px;">@Localizer["Kontakt"]</h2>
</div>
<br />

<br />
<div class="row">
    <div class="col-md-3">
        <div class="contact-category">
            <h3>
                <img src="~/images/laptop.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Sklep internetowy" />
                @Localizer["shops"]
            </h3>
            <p><a href="mailto:techstore@wp.pl">Techstore@wp.pl</a></p>
            <p><a href="tel:+48699699699">+48 699 699 699</a></p>
            <p><em>@Localizer["days1"]</em> ---> 8:30-21:30<br /><em>@Localizer["days2"]</em> ---> 9:30-19:30</p>
        </div>
    </div>

    <div class="col-md-3">
        <div class="contact-category">
            <h3>
                <img src="~/images/serwis.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Serwis" />

                @Localizer["service"]
            </h3>
            <p><a href="mailto:serwis.techstore@wp.pl">serwis.techstore@wp.pl</a></p>
            <p><a href="tel:+48420420420">+48 420 420 420</a></p>
            <p><em>@Localizer["days1"]</em> ---> <em>10:30-19:30</em><br /><em>@Localizer["days2"]</em> ---> <em>11:30-18:30</em></p>
        </div>
    </div>


    <div class="col-md-3">
        <div class="contact-category">
            <h3>
                <img src="~/images/chat.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Chat" />

                @Localizer["chat"]
            </h3>
            <p><a href="https://api.whatsapp.com/send?phone=696969699">@Localizer["whatsapp"]</a></p>
        </div>
    </div>


    <div class="col-md-3">
        <div class="contact-category">
            <h3>
                <img src="~/images/geo.svg" class="icon-dark-mode" style="width: 1em; height: 1em; vertical-align: middle;" alt="Adres" />

                @Localizer["adress"]
            </h3>
            <p>ul. Prószkowska 4</p>
            <p>Opole 45-048</p>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12 divider"></div>
</div>

<div>
    <h3>@Localizer["head1"]</h3>
    <br />
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2529.5460948920904!2d17.900172588275595!3d50.654120499543325!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471053bb1bcdafab%3A0xf2ef41915344d5dd!2sPolitechnika%20Opolska!5e0!3m2!1spl!2spl!4v1699726378626!5m2!1spl!2spl" width="100%" height="500" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>

<div class="row">
    <div class="col-md-12 divider"></div>
</div>

<form method="post">
    <div class="form-group">
        <label for="title">@Localizer["title"]</label>
        <input type="text" class="form-control" id="title" asp-for="@Model.report.Title">
    </div>
    <div class="form-group">
        <label for="description">@Localizer["description"]</label>
        <textarea class="form-control" id="description" rows="5" asp-for="@Model.report.Description"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Zapisz</button>
</form>



<script src="~/js/contact-form.js"></script>

TechStore/Pages/Productdetail.cshtml
@page "/ProductDetails/{id:int}"
@using TechStore.Pages
@model TechStore.Pages.OpiniaPageModel
@using TechStore.Models
@using TechStore.Repositories
@inject IOpiniaRepository OpiniaRepository
@{
    ViewData["Title"] = "Szczegółowy opis produktu";
    var productId = Model.Id;
    var opinie = OpiniaRepository.GetAllOpinie();
    var liczbaOpinii = opinie.Count();

}


<link rel="stylesheet" href="~/css/product-details.css" />
<script src="~/js/product-details.js" defer></script>

<div class="product-page-container">
    <div class="carousel-container">
        <div class="carousel-slide">
            <img src= "@Model.Product.Image" alt="Realme C55-1" class="carousel-image">
            <img src="@Model.ProductSpecification.Picture2" alt="Realme C55-2" class="carousel-image">
            <img src="@Model.ProductSpecification.Picture3" alt="Realme C55-3" class="carousel-image">
          
        </div>
        <a class="prev" onclick="moveSlide(-1)">&#10094;</a>
        <a class="next" onclick="moveSlide(1)">&#10095;</a>
    </div>
    <div class="product-details-container">
       

            <h1 class="product-title"><strong>@Model.Product.Name</strong></h1>

            <div class="product-info-container">
                <div class="product-specs">
                @if (Model.Product.CategoryId == 1) 
                {
                    <p><strong>System:</strong> @Model.ProductSpecification.Parametr1</p>
                    <p><strong>RAM:</strong> @Model.ProductSpecification.Parametr2</p>
                    <p><strong>Procesor:</strong> @Model.ProductSpecification.Parametr3</p>
                    <p><strong>Pamięć wewntęrzna:</strong> @Model.ProductSpecification.Parametr4</p>
                    <p><strong>Karta Graficzna:</strong> @Model.ProductSpecification.Parametr5</p>
                    <p><strong>Matryca:</strong> @Model.ProductSpecification.Parametr6</p>
                    <p><strong>Gwarancja:</strong> @Model.ProductSpecification.Parametr7</p>

                }
                else if (Model.Product.CategoryId == 2) 
                {
                    <p><strong>System:</strong> @Model.ProductSpecification.Parametr1</p>
                    <p><strong>RAM:</strong> @Model.ProductSpecification.Parametr2</p>
                    <p><strong>Procesor:</strong> @Model.ProductSpecification.Parametr3</p>
                    <p><strong>Pamięć wbudowana:</strong> @Model.ProductSpecification.Parametr4</p>
                    <p><strong>Aparat:</strong> @Model.ProductSpecification.Parametr5</p>
                    <p><strong>Wyświetlacz:</strong> @Model.ProductSpecification.Parametr6</p>
                    <p><strong>Łączność:</strong> @Model.ProductSpecification.Parametr7</p>
                }

                else if (Model.Product.CategoryId == 3) 
                {
                    <p><strong>System:</strong> @Model.ProductSpecification.Parametr1</p>
                    <p><strong>RAM:</strong> @Model.ProductSpecification.Parametr2</p>
                    <p><strong>Procesor:</strong> @Model.ProductSpecification.Parametr3</p>
                    <p><strong>Pamięć wewnętrzna:</strong> @Model.ProductSpecification.Parametr4</p>
                    <p><strong>Karta Graficzna:</strong> @Model.ProductSpecification.Parametr5</p>
                    <p><strong>Moc zasilacza:</strong> @Model.ProductSpecification.Parametr6</p>
                    <p><strong>Dodatkowe wyposażenie:</strong> @Model.ProductSpecification.Parametr7</p>
                }

                else if (Model.Product.CategoryId == 7) 
                {
                    <p><strong>Zastosowanie:</strong> @Model.ProductSpecification.Parametr1</p>
                    <p><strong>Kolor:</strong> @Model.ProductSpecification.Parametr2</p>
                    <p><strong>Gwarancja:</strong> @Model.ProductSpecification.Parametr3</p>
                }
                
            </div>
            
            </div>

            </div>
        
    <div class="price-action-container">
        @if (Model.Product.IsOnSale)
        {
            <p class="price">@Model.Product.SalePrice PLN<br /><span class="oldprice">@Model.Product.Price PLN</span></p>
            }
            else{
            <p class="price">@Model.Product.Price PLN</p>
            }
        <form method="post" asp-page-handler="AddToSession">
            <input type="hidden" asp-for="Id" />
            <button class="add-to-cart-button" type="submit">
                Dodaj do koszyka
                <img src="~/images/cart-submit.svg" alt="Cart" class="icon" />
            </button>
        </form>
        <button class="add-to-favorites-button">
            <img src="~/images/heart.svg" alt="Add to Favorites" class="icon" />
        </button>
        <div class="delivery-info-container">
            <p class="delivery-info">
                Dostawa za 24 h
                <img src="~/images/serwis.svg" alt="Delivery" class="icon" />
            </p>
        </div>
    </div>

    <div class="tab-navigation">
        <a href="#description">Opis</a>
        <a href="#specification">Specyfikacja techniczna</a>
        <a href="#reviews">Opinie</a>
    </div>
</div>
<div class="productdetails">
    <div id="description">
        <h2 class="section-title">Opis urządzenia</h2>
        <div class="description-section">
            <p class="section-subtitle">@Model.ProductSpecification.Header1</p>
            <img src="@Model.ProductSpecification.Picture6" alt="Realme C55-6" class="description-image">
        </div>

        <div class="row">
            <div class="col-md-12 divider"></div>
        </div>

        <div class="description-section">
            <p class="section-subtitle">@Model.ProductSpecification.Header2</p>
            @Model.ProductSpecification.Description1 <br />
            <img src="@Model.ProductSpecification.Picture7" alt="Realme C55-7" class="description-image">
        </div>


        <div class="row">
            <div class="col-md-12 divider"></div>
        </div>

        <div class="description-section">
            <p class="section-subtitle">@Model.ProductSpecification.Header3</p>
            @Model.ProductSpecification.Description2  <br />
            <img src="@Model.ProductSpecification.Picture8" alt="Realme C55-8" class="description-image">
        </div>

        <div class="row">
            <div class="col-md-12 divider"></div>
        </div>

    </div>
</div>

<div id="specification">
    <h2 class="section-title">Specyfikacja techniczna</h2>

    <table class="spec-table">

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>

        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
        <tr>
            <th>Parametr</th>
            <td>Dane</td>

        </tr>
    </table>
</div>
<br />

<div id="reviews">
    <h2>Opinie</h2>
    <div class="average-rating">
        <div class="rating-value">
            <span class="rating-number">5</span>/5
            <div class="stars">★★★★★</div>
        </div>
        <div class="rating-count">@liczbaOpinii Opini</div>
        <div class="recommendation-count">@liczbaOpinii użytkowników poleca ten produkt</div>

        <div class="add-review">
            <span>Masz ten produkt? Pomóż innym w wyborze, dodaj swoją opinię.</span>
            <a href="#review-form" class="add-review-button">Dodaj opinię</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 divider"></div>
    </div>

    <div class="user-reviews-container">


        <div class="user-reviews-container">
            @foreach (var opinia in opinie)
            {
                <div class="user-review">

                    <h3>@opinia.Name</h3><br>
                    <p class="opinion-title">@opinia.Title</p>
                    <p class="opinion-description">@opinia.Description</p> <br>
                    <p>Ocena jakości: @opinia.Quality</p>
                    <p>Ocena funkcjonalności: @opinia.Function</p>

                    @{
                        var overallRating = (opinia.Quality + opinia.Function) / 2.0;
                    }

                    <p>Ocena ogólna: @overallRating</p> <br> <br> <br>
                    <p>Opublikowano: @opinia.Data.ToString("dd MMM yyyy")</p>
                    <hr />
                </div>
            }
        </div>
    </div>

    <div class="review-form-and-ratings-container">
        <div class="review-form-container">
            <h2>Podziel się swoją opinią</h2>
            <form method="post" id="review-form">
                <div class="form-row">
                    <span class="stars">★★★★★</span>
                </div>
                <div class="form-row">
                    <label asp-for="Opinia.Name">Imię/Nick *</label>
                    <input asp-for="Opinia.Name" type="text" id="Opinia.Name" name="Opinia.Name" required>
                </div>
                <div class="form-row">
                    <label asp-for="Opinia.Email">Email *</label>
                    <input asp-for="Opinia.Email" type="email" id="Opinia.Email" name="Opinia.Email" required>
                </div>
                <div class="form-row">
                    <label asp-for="Opinia.Title">Tytuł opinii *</label>
                    <input asp-for="Opinia.Title" type="text" id="Opinia.Title" name="Opinia.Title" required>
                </div>
                <div class="form-row">
                    <label asp-for="Opinia.Description">Napisz swoją opinię o produkcie *</label>
                    <textarea asp-for="Opinia.Description" id="Opinia_Description" name="Opinia.Description" required></textarea>
                </div>




                <div class="individual-rating-container">
                    <span>Jakość</span>
                    <div class="stars-overview" data-category="quality">
                        @for (int i = 1; i <= 5; i++)
                        {
                            <span class="star" data-value="@i">★</span>
                        }
                        <span class="rating-result">0/5</span>
                    </div>
                </div>


                <div class="individual-rating-container">
                    <span>Funkcje</span>
                    <div class="stars-overview" data-category="features">
                        @for (int i = 1; i <= 5; i++)
                        {
                            <span class="star" data-value="@i">★</span>
                        }
                        <span class="rating-result">0/5</span>
                    </div>
                </div>

                <br /><div class="form-row">
                    <button type="submit" class="submit-button" id="wyslijWiadomosc">Prześlij</button>
                </div>
                <input asp-for="Opinia.Quality" type="hidden" name="Opinia.Quality" id="Quality" value="0" required>
                <input asp-for="Opinia.Function" type="hidden" name="Opinia.Function" id="Function" value="0" required>
                <input asp-for="Opinia.Overall" type="hidden" name="Opinia.Overall" id="Overall" value="0" required>
            </form>
        </div>
    </div>
</div>